name: Benchmark Hyper Threading

on:
  pull_request:
    branches: [ '**' ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Python3 Build
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install test dependencies
      run: |
        pip install -r requirements.txt
        sudo apt update

    - name: Install Rust
      uses: dtolnay/rust-toolchain@1.74.1
      with:
          components: rustfmt, clippy

    - name: Run Benchmarks
      run: |
        chmod +x examples/hyper_threading/hyper-threading-workflow.sh
        echo "Benchmarking PR..."
        sh examples/hyper_threading/hyper-threading-workflow.sh > results_pr.txt

    - name: Compare Results
      run: |
        echo "PR Results:"
        cat results_pr.txt

    - name: Upload Results
      uses: actions/upload-artifact@master
      with:
        name: benchmark-results
        path: |
          results_pr.txt
